import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <img src="/PokePart1.png" alt="Parte 1 do pokedex" />
          <img src="/PokePart23.png" alt="Parte 2 do pokedex" />
        </div>
      </main>
    </>
  )
}
